### ISSUE TITLE
Logon Error Parsing

### ISSUE THREAD

**Issue by n2x4** [PwC-IR/Blue-team-app-Office-365-and-Azure#1]
Would it be possible to adjust the logon reporting to take LogonErrors into account?  The 365 audit log doesn't do a great job of differentiating between a successful login and one that failed without also reviewing if a LogonError key exists.  As of now, the logon report shows both successful and failed logins since the LogonError key isn't considered.  I think this should be solvable with adjustments to the search query, but I'm not versed enough to adjust it myself.

Thank you for an awesome Splunk app, btw!  It's a great starting point for IR analysis in 365.

**Comment by PwC-IR** [comment]
Hi,

Thank you for the feedback, and you're correct it's pretty difficult to identify succesfull logins, because even if there's no LogonError it can be a fail. I'm happy to see if I can improve the searches, do you have a suggestion?

**Comment by n2x4** [comment]
I've been experimenting with some small changes to the successful login query and so far have had some success in narrowing down the results.  

- I've changed the Successful logins per country query from LogonError!=UserAccountNotFound to LogonError!=*.  In my testing I've not noticed any valid logins I've missed due to this query change.

- As a sanity check I also run a separate query to return the distinct LogonError values and see if there's anything special I'm missing.

- I've been evaluating if there's any usefulness in adding the "Success" value to my query, but don't have enough testing done to be sure.

**Comment by PwC-IR** [comment]
Hi,

Thanks for that and someone else also changed it to NOT LogonError="*" which is the same as what != does. Will do some testing with that, I think I need to change that.
I don't think the succes value helps, also look at this: https://cybersecurity.att.com/documentation/usm-anywhere/alienapps-guide/office-365/office-365-userloggedin-event-discrepancy.htm 
Also if you do a search for Success you'll seen aan explanation by Microsoft around the Success message:
https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#azure-active-directory-account-logon-schema

**Comment by PwC-IR** [comment]
I'd like you to test the following query to see if you get all valid logons:
index=* eventtype="user_logins"  | spath input=AuditData | eval User = coalesce(UserId, UserIds) | search Workload=AzureActiveDirectory User!=Unknown LogonError=None

**Comment by n2x4** [comment]
Sorry for the late reply - I've been testing this query on a few incident reviews and so far it looks to be working.

**Comment by PwC-IR** [comment]
@n2x4 I've also uploaded the default directory from the app, so if you have any improvements for searches please check out the various views containing the searches.
