### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by jbeley** [PwC-IR/Blue-team-app-Office-365-and-Azure#2]
I'd like to do a pull request with some of the enhancements I've made to this application, however, using the spl file make it difficult to merge the changes. Would you be open to decompressing the SPL file tracking the individual configuration files?

**Comment by PwC-IR** [comment]
Hi jbeley,

Sorry for the late response. The app is mostly maintained on Splunkbase: https://splunkbase.splunk.com/app/4667/
I'll upload a decompressed version here soon.

**Comment by PwC-IR** [comment]
@jbeley github contains default dir with all searches as an FYI searches use the following hierarchy:

Macro search(select right index)-Eventtype(get subset of data and basic parsing)-Searches(additional parsing and filtering).
