### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Aevyz** [PwC-IR/Blue-team-app-Office-365-and-Azure#5]
Hey, 

we were interested in using and adding a few features to your Splunk App. We were wondering what kind of a License your software has. Can we fork it, and modify the code?

https://choosealicense.com/no-permission/

**Comment by invictus-korstiaan** [comment]
Hi there you can do whatever you like with it :) I'll add a license to the repo as well. What are you going to add/modify? If it's something useful for other people you can also do a PR and we can maybe integrate it. I haven't developed much new features lately, so curious to hear your input.

**Comment by Aevyz** [comment]
Hey @invictus-korstiaan, sorry for the late reply. Thanks so much for adding the license. Makes things easier.

I was planning on changing how the macros work. For our use case, it is kind of annoying to change the macro every single time you have a new index. So I want to add in a dropdown field that lets you select the index. 

Not quite sure if its PR-able since it would involve changing how the system works for everyone, which would not be ideal, but I'll give you guys notice once I implement it. Maybe we can find a way to "generalize" it, without breaking the old default behavior.
